version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: 'Setup environment'
          command: |
            apt update
            apt install --yes make
      - run:
          name: 'Tests'
          command: |
            make
